### ISSUE TITLE
Debugger Freezing/Debug Actions Not Working in Visual Studio

### ISSUE THREAD

**Issue by lordmilko** [phoityne/haskell-debug-adapter#12]
I am trying to get Haskell debugging working in Visual Studio.

The [hdx4vs](https://github.com/phoityne/hdx4vs) extension (which is a bit out of date) appears to have the following issues when I go to use it
* Refers to the old `phoityne-vscode` executable instead of `haskell-debug-adapter` (easily fixed)
* Visual Studio hangs saying "a debugger operation is taking a long time to complete" indefinitely

I have been trying to investigate where the issue is here, and whether the issue is specific to `haskell-debug-adapter`, the `hdx4vs` VSIX, or Visual Studio itself.

As Visual Studio has the ability to run external debug adapters directly from the *Command Window* pane, one should be able to [use the techniques](https://github.com/microsoft/VSDebugAdapterHost/wiki/Quickly-Testing-a-Debug-Adapter-in-Visual-Studio) described by Microsoft to load the adapter and test that it works.

When it comes to the haskell-debug-adapter however
* Attempting to do this in Visual Studio 2017 causes the debugger to hang with the "debugger operation is taking a long time to complete" message, just like you see when trying to use hdx4vs
* Attempting to do this in Visual Studio 2019 gets you to the first breakpoint you hit, however attempting to perform any additional operations afterwards, such as
    * Continuing to another break point (F5)
    * Stepping in (F11)
    * Stepping over (F10)

    does not work. If I open the same project in Visual Studio Code everything works fine, so it is not clear to me what the issue is.

To try and resolve this I have been trying to compare the log file generated by `haskell-debug-adapter` running under Visual Studio to the one from Visual Studio Code; while I have found a few small differences, correcting those hasn't amounted to much.

The following is a list of steps you should be able to take to reproduce the issue

1. Download the attached file `debugExample.zip`
2. Extract to C:\ drive
3. In `C:\debugExample\launch.json` replace `<stackBin>` in the `$adapter$` property with path to the folder containing `haskell-debug-adapter.exe`, e.g.
   ```json
   "$adapter": "C:\\Users\\Administrator\\AppData\\Roaming\\local\\bin\\haskell-debug-adapter.exe",
   ```
4. Open Visual Studio, navigate to File -> Open -> Folder -> C:\debugExample
5. Open the file `src\Main.hs` and set a breakpoint on line 5 (`putStrLn "hello world"`)
6. Navigate to View -> Other Windows -> Command Window
7. In the Command Window run the following commands

```
DebugAdapterHost.Logging /On /OutputWindow
DebugAdapterHost.Launch /LaunchJson:C:\debugExample\launch.json
```

On my system I hit the breakpoint, but when I hit F10 it just fails and the debugger never ends

Attached is the log generated from running with Visual Studio 2019, where attempting to step does not work. I am successfully able to step through the test file of the [VSDebugAdapterHost](https://github.com/microsoft/VSDebugAdapterHost) sample, so the DAP client integrated in Visual Studio is capable of stepping with other providers.

Are you potentially able to provide any insights as to what's going on?

[debugExample.zip](https://github.com/phoityne/haskell-debug-adapter/files/4673704/debugExample.zip)

[phoityne.log](https://github.com/phoityne/haskell-debug-adapter/files/4673744/phoityne.log)

**Comment by phoityne** [comment]
Thanks for trying hdx4vs.
From phoityne.log, after stackTrace response to VS, 

```
2020-05-25 00:50:41.293111300000 [$pid(ThreadId 6)] DEBUG RESPONSE - sink get data. {"seq":85,"type":"event","event":"stopped","body":{"reason":"breakpoint","description":"","threadId":0,"text":"","allThreadsStopped":true}}
2020-05-25 00:50:41.446120100000 [$pid(ThreadId 6)] DEBUG RESPONSE - sink get data. {"seq":94,"type":"response","request_seq":13,"success":true,"command":"stackTrace",
```

VS did not request "scopes request" to the debug adapter.
As a result, on VS, it does not hit the next step.
I don't find out why VS does not request "scops request".

By the way, after continue request, VS requested "scops request", so hit the break (the first one).

```
2020-05-25 00:50:39.381002000000 [$pid(ThreadId 6)] DEBUG RESPONSE - sink get data. {"seq":61,"type":"event","event":"stopped","body":{"reason":"breakpoint","description":"","threadId":0,"text":"","allThreadsStopped":true}}
2020-05-25 00:50:39.740022500000 [$pid(ThreadId 6)] DEBUG RESPONSE - sink get data. {"seq":74,"type":"response","request_seq":9,"success":true,"command":"stackTrace",
2020-05-25 00:50:40.205049100000 [$pid(ThreadId 4)] DEBUG REQUEST - lbs2req get data. {"type":"request","command":"scopes","arguments":{"frameId":0},"seq":10}
```

**Comment by lordmilko** [comment]
Hi @phoityne,

Thanks for your response. When run under vscode, the debugger steps successfully without appearing to generating a "scopes request" *ever*.

In the attached log from vscode, the word "scope" does not seem to appear in the file at all

[phoityne_vscode.log](https://github.com/phoityne/haskell-debug-adapter/files/4678947/phoityne_vscode.log)

**Comment by phoityne** [comment]
I reproduced and understood the issue.
This is hda's bug.
There is a sequence problem between VS and hda.

By verbose option, we can see the debug log of VSDebugAdapterHost.

```
DebugAdapterHost.Logging /On /OutputWindow /Verbosity:debug
```

After F10, there are some warnings.
```
 1> State: Paused => Resuming
 1> [DebugAdapter] --> C (next-10): {"type":"request","command":"next","arguments":{"threadId":0},"seq":10}
 1> [DebugAdapter] <--   E (stopped): {"seq":83,"type":"event","event":"stopped","body":{"reason":"breakpoint","description":"","threadId":0,"text":"","allThreadsStopped":true}}
 1> State: Resuming => Pausing
 1> WARNING: Unexpected process state 'Resuming' - expected one of 'Running'
 1> [DebugAdapter] --> C (threads-11): {"type":"request","command":"threads","arguments":{},"seq":11}
 1> [DebugAdapter] <--   R (next-10) [86 ms]: {"seq":84,"type":"response","request_seq":10,"success":true,"command":"next","message":""}
 1> State: Pausing => Running
 1> WARNING: Unexpected process state 'Pausing' - expected one of 'Initializing', 'Resuming'
``` 
hda [has to respond "next response"](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Next) before throwing stopped event.

Regards.

**Comment by phoityne** [comment]
Thank you for the report.
Fixed.
